import { Image } from './image';
import { ImageMetaData } from './image-meta-data';

export const imageMetaData: ImageMetaData[] = [
    {
        _id: 'mock1',
        name: 'mock1',
        tags: [],
    },
    {
        _id: 'mock2',
        name: 'mock2',
        tags: ['t1', 't2'],
    },
];

export const images: Image[] = [
    {
        metaData: imageMetaData[0],
        data:
            'iVBORw0KGgoAAAANSUhEUgAAAx0AAACbCAYAAAAHmPbLAAAD3ElEQVR4nO3dP8iVZRjH8e8iKO/iFAgODSI4tDQYDoHQIghO79AiOioitAQ5SS5Fo2AILmJLW0gEbjmEgZCbuCRtBs6CbjVcT+QSRud934OnzwduzsPz53Cd7fy47vu5CwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADYSaerq9X2ugsBAAA201+h48EyhA8AAGDXbPd3+LhcfVQdWmtFAADARtquvq7uV8+XcX85d7H6oNq3ptoAAIANdKjpelyublW/VH8sn7eqS9WH1cF1FQgAAGyefU3H42J1s5mS9aJ6Wn1XXWs6JkfXVSAAALCZjjZh41oTPp42YeRBE06sFQEAAHbcwWb61aX+ea2IMAIAAOy419eKCCMAAMCeEUYAAIC1+Ddh5NPqfLPp4fHq3WprrwsFAAA2y+th5KvqdvVD9bD6rVnI/mI5frhcu73c+0l1pnov4QQAAFjBVtP1ON50Qc43XZHr1ffV4+pl9az6qbpTfV6daxbBH97rggEAgM10uAkZ55rQcacJIc+aUPK4CSnXq8+qC9XH1anqRHWs6bwc2OvCAQCAt99WMw3rTDMt68tm75Fvq3vVz9WT6vcmoLxcjp8s1+4t995cnhVaAACAlRxoAsSxJlCcagLGhSZwrBparjR7n5xtgtDJ6v3qSPVOtX/XfyEAAPBWe1No+aK6UX1T3a1+rB5VvzZv9Hq1jOfLuUfLPXeXZ24s36HjAgAA/Gf7m67HkaYLcrLpipxtuiRXWr3jctX4X4/TAQDAit7UcVn3n15D6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGCX/Al4phFHMlxrWAAAAABJRU5ErkJggg==',
    },
    {
        metaData: imageMetaData[1],
        data:
            'iVBORw0KGgoAAAANSUhEUgAAAx0AAACbCAYAAAAHmPbLAAACrUlEQVR4nO3ZMQoCQRBFwb75HG2vZqTCLGIwPjCogp/0DR49AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDL+jIAAIAja2auucfG8wYAAHDk00fDpwMAAPgJ0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABASnQAAAAp0QEAAKREBwAAkBIdAABAas3MNe/IWNsNAADgyB4b+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODPPAAQd4/hw6bGagAAAABJRU5ErkJggg==',
    },
];
